version: '3'

services:
  web:
    image: nginx
    volumes:
      - "./:/var/www/app:ro"
      - "./docker/web/vhost.conf:/etc/nginx/conf.d/default.conf:ro"

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GUID: ${GUID:-1000}
        TZ: ${TZ:-Europe/Moscow}
    volumes:
      - "./:/var/www/app"
      - "./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    env_file:
      - .env.default
      - .env

  php:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GUID: ${GUID:-1000}
        TZ: ${TZ:-Europe/Moscow}
    volumes:
      - "./:/var/www/app"
      - "./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    env_file:
      - .env.default
      - .env

  db:
    image: mariadb
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - .env.default
      - .env

  memcached:
    image: memcached
    restart: always

volumes:
  db_data:
    driver: local
